//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Istu.Elma.Auth.ElmaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebData", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Istu.Elma.Auth.ElmaServiceReference.WebDataItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Istu.Elma.Auth.ElmaServiceReference.WebDataItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebDataItem", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WebDataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Istu.Elma.Auth.ElmaServiceReference.WebData DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Istu.Elma.Auth.ElmaServiceReference.WebData[] DataArrayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData[] DataArray {
            get {
                return this.DataArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.DataArrayField, value) != true)) {
                    this.DataArrayField = value;
                    this.RaisePropertyChanged("DataArray");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class TaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private long ExecutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutorNameField;
        
        private System.DateTime CreationDateField;
        
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Istu.Elma.Auth.ElmaServiceReference.ConnectorInfo[] ConnectorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ExecutorId {
            get {
                return this.ExecutorIdField;
            }
            set {
                if ((this.ExecutorIdField.Equals(value) != true)) {
                    this.ExecutorIdField = value;
                    this.RaisePropertyChanged("ExecutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExecutorName {
            get {
                return this.ExecutorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutorNameField, value) != true)) {
                    this.ExecutorNameField = value;
                    this.RaisePropertyChanged("ExecutorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Istu.Elma.Auth.ElmaServiceReference.ConnectorInfo[] ConnectorInfo {
            get {
                return this.ConnectorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectorInfoField, value) != true)) {
                    this.ConnectorInfoField = value;
                    this.RaisePropertyChanged("ConnectorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectorInfo", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class ConnectorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowMessageSendResult", Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    [System.SerializableAttribute()]
    public partial class WorkflowMessageSendResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReceivedCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReceivedCount {
            get {
                return this.ReceivedCountField;
            }
            set {
                if ((this.ReceivedCountField.Equals(value) != true)) {
                    this.ReceivedCountField = value;
                    this.RaisePropertyChanged("ReceivedCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/", ConfigurationName="ElmaServiceReference.WFPWebServiceSoap")]
    public interface WFPWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.RunResponse Run(Istu.Elma.Auth.ElmaServiceReference.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Run", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.RunResponse> RunAsync(Istu.Elma.Auth.ElmaServiceReference.RunRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse GetStatus(Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse> GetStatusAsync(Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse LoadContext(Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/LoadContext", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse> LoadContextAsync(Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse GetActiveTasks(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/GetActiveTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse> GetActiveTasksAsync(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse ExecuteTask(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/ExecuteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse> ExecuteTaskAsync(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse SaveContext(Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SaveContext", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse> SaveContextAsync(Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.TerminateResponse Terminate(Istu.Elma.Auth.ElmaServiceReference.TerminateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/Terminate", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.TerminateResponse> TerminateAsync(Istu.Elma.Auth.ElmaServiceReference.TerminateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse SendMessage(Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse> SendMessageAsync(Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем userName из пространства имен http://www.elma-bpm.ru/WFPWebService/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse SendMessageToInstance(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elma-bpm.ru/WFPWebService/SendMessageToInstance", ReplyAction="*")]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse> SendMessageToInstanceAsync(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.RunRequestBody Body;
        
        public RunRequest() {
        }
        
        public RunRequest(Istu.Elma.Auth.ElmaServiceReference.RunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string instanceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData data;
        
        public RunRequestBody() {
        }
        
        public RunRequestBody(string userName, string password, string token, string instanceName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            this.userName = userName;
            this.password = password;
            this.token = token;
            this.instanceName = instanceName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.RunResponseBody Body;
        
        public RunResponse() {
        }
        
        public RunResponse(Istu.Elma.Auth.ElmaServiceReference.RunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class RunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RunResult;
        
        public RunResponseBody() {
        }
        
        public RunResponseBody(long RunResult) {
            this.RunResult = RunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(Istu.Elma.Auth.ElmaServiceReference.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Istu.Elma.Auth.ElmaServiceReference.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(int GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.LoadContextRequestBody Body;
        
        public LoadContextRequest() {
        }
        
        public LoadContextRequest(Istu.Elma.Auth.ElmaServiceReference.LoadContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public LoadContextRequestBody() {
        }
        
        public LoadContextRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.LoadContextResponseBody Body;
        
        public LoadContextResponse() {
        }
        
        public LoadContextResponse(Istu.Elma.Auth.ElmaServiceReference.LoadContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class LoadContextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData LoadContextResult;
        
        public LoadContextResponseBody() {
        }
        
        public LoadContextResponseBody(Istu.Elma.Auth.ElmaServiceReference.WebData LoadContextResult) {
            this.LoadContextResult = LoadContextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasks", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequestBody Body;
        
        public GetActiveTasksRequest() {
        }
        
        public GetActiveTasksRequest(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        public GetActiveTasksRequestBody() {
        }
        
        public GetActiveTasksRequestBody(string userName, string password, long instanceId) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveTasksResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponseBody Body;
        
        public GetActiveTasksResponse() {
        }
        
        public GetActiveTasksResponse(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class GetActiveTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.TaskInfo[] GetActiveTasksResult;
        
        public GetActiveTasksResponseBody() {
        }
        
        public GetActiveTasksResponseBody(Istu.Elma.Auth.ElmaServiceReference.TaskInfo[] GetActiveTasksResult) {
            this.GetActiveTasksResult = GetActiveTasksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTask", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequestBody Body;
        
        public ExecuteTaskRequest() {
        }
        
        public ExecuteTaskRequest(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class ExecuteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long taskId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string connectorUid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData data;
        
        public ExecuteTaskRequestBody() {
        }
        
        public ExecuteTaskRequestBody(string userName, string password, long taskId, string connectorUid, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            this.userName = userName;
            this.password = password;
            this.taskId = taskId;
            this.connectorUid = connectorUid;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteTaskResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponseBody Body;
        
        public ExecuteTaskResponse() {
        }
        
        public ExecuteTaskResponse(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteTaskResponseBody {
        
        public ExecuteTaskResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContext", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SaveContextRequestBody Body;
        
        public SaveContextRequest() {
        }
        
        public SaveContextRequest(Istu.Elma.Auth.ElmaServiceReference.SaveContextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SaveContextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData data;
        
        public SaveContextRequestBody() {
        }
        
        public SaveContextRequestBody(string userName, string password, long instanceId, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContextResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SaveContextResponseBody Body;
        
        public SaveContextResponse() {
        }
        
        public SaveContextResponse(Istu.Elma.Auth.ElmaServiceReference.SaveContextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveContextResponseBody {
        
        public SaveContextResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Terminate", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.TerminateRequestBody Body;
        
        public TerminateRequest() {
        }
        
        public TerminateRequest(Istu.Elma.Auth.ElmaServiceReference.TerminateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class TerminateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reason;
        
        public TerminateRequestBody() {
        }
        
        public TerminateRequestBody(string userName, string password, long instanceId, string reason) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.TerminateResponseBody Body;
        
        public TerminateResponse() {
        }
        
        public TerminateResponse(Istu.Elma.Auth.ElmaServiceReference.TerminateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TerminateResponseBody {
        
        public TerminateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Istu.Elma.Auth.ElmaServiceReference.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData data;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string userName, string password, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            this.userName = userName;
            this.password = password;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Istu.Elma.Auth.ElmaServiceReference.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstance", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequestBody Body;
        
        public SendMessageToInstanceRequest() {
        }
        
        public SendMessageToInstanceRequest(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long instanceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Istu.Elma.Auth.ElmaServiceReference.WebData data;
        
        public SendMessageToInstanceRequestBody() {
        }
        
        public SendMessageToInstanceRequestBody(string userName, string password, long instanceId, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            this.userName = userName;
            this.password = password;
            this.instanceId = instanceId;
            this.messageTypeName = messageTypeName;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageToInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageToInstanceResponse", Namespace="http://www.elma-bpm.ru/WFPWebService/", Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponseBody Body;
        
        public SendMessageToInstanceResponse() {
        }
        
        public SendMessageToInstanceResponse(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.elma-bpm.ru/WFPWebService/")]
    public partial class SendMessageToInstanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessageToInstanceResult;
        
        public SendMessageToInstanceResponseBody() {
        }
        
        public SendMessageToInstanceResponseBody(Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessageToInstanceResult) {
            this.SendMessageToInstanceResult = SendMessageToInstanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFPWebServiceSoapChannel : Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFPWebServiceSoapClient : System.ServiceModel.ClientBase<Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap>, Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap {
        
        public WFPWebServiceSoapClient() {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.RunResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.Run(Istu.Elma.Auth.ElmaServiceReference.RunRequest request) {
            return base.Channel.Run(request);
        }
        
        public long Run(string userName, string password, string token, string instanceName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.RunRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.RunRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            Istu.Elma.Auth.ElmaServiceReference.RunResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.RunResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.RunAsync(Istu.Elma.Auth.ElmaServiceReference.RunRequest request) {
            return base.Channel.RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.RunResponse> RunAsync(string userName, string password, string token, string instanceName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.RunRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.RunRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.RunRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.instanceName = instanceName;
            inValue.Body.data = data;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).RunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.GetStatus(Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public int GetStatus(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.GetStatusAsync(Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetStatusResponse> GetStatusAsync(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.GetStatusRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.GetStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.LoadContext(Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest request) {
            return base.Channel.LoadContext(request);
        }
        
        public Istu.Elma.Auth.ElmaServiceReference.WebData LoadContext(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).LoadContext(inValue);
            return retVal.Body.LoadContextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.LoadContextAsync(Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest request) {
            return base.Channel.LoadContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.LoadContextResponse> LoadContextAsync(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.LoadContextRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.LoadContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).LoadContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.GetActiveTasks(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasks(request);
        }
        
        public Istu.Elma.Auth.ElmaServiceReference.TaskInfo[] GetActiveTasks(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).GetActiveTasks(inValue);
            return retVal.Body.GetActiveTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.GetActiveTasksAsync(Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest request) {
            return base.Channel.GetActiveTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksResponse> GetActiveTasksAsync(string userName, string password, long instanceId) {
            Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.GetActiveTasksRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).GetActiveTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.ExecuteTask(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTask(request);
        }
        
        public void ExecuteTask(string userName, string password, long taskId, string connectorUid, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).ExecuteTask(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.ExecuteTaskAsync(Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest request) {
            return base.Channel.ExecuteTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskResponse> ExecuteTaskAsync(string userName, string password, long taskId, string connectorUid, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.ExecuteTaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.taskId = taskId;
            inValue.Body.connectorUid = connectorUid;
            inValue.Body.data = data;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).ExecuteTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SaveContext(Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest request) {
            return base.Channel.SaveContext(request);
        }
        
        public void SaveContext(string userName, string password, long instanceId, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SaveContext(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SaveContextAsync(Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest request) {
            return base.Channel.SaveContextAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SaveContextResponse> SaveContextAsync(string userName, string password, long instanceId, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SaveContextRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SaveContextRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.data = data;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SaveContextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.TerminateResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.Terminate(Istu.Elma.Auth.ElmaServiceReference.TerminateRequest request) {
            return base.Channel.Terminate(request);
        }
        
        public void Terminate(string userName, string password, long instanceId, string reason) {
            Istu.Elma.Auth.ElmaServiceReference.TerminateRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.TerminateRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            Istu.Elma.Auth.ElmaServiceReference.TerminateResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).Terminate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.TerminateResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.TerminateAsync(Istu.Elma.Auth.ElmaServiceReference.TerminateRequest request) {
            return base.Channel.TerminateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.TerminateResponse> TerminateAsync(string userName, string password, long instanceId, string reason) {
            Istu.Elma.Auth.ElmaServiceReference.TerminateRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.TerminateRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.TerminateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.reason = reason;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).TerminateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SendMessage(Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessage(string userName, string password, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SendMessageAsync(Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageResponse> SendMessageAsync(string userName, string password, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SendMessageRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SendMessageRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SendMessageToInstance(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstance(request);
        }
        
        public Istu.Elma.Auth.ElmaServiceReference.WorkflowMessageSendResult SendMessageToInstance(string userName, string password, long instanceId, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse retVal = ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SendMessageToInstance(inValue);
            return retVal.Body.SendMessageToInstanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse> Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap.SendMessageToInstanceAsync(Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest request) {
            return base.Channel.SendMessageToInstanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceResponse> SendMessageToInstanceAsync(string userName, string password, long instanceId, string messageTypeName, Istu.Elma.Auth.ElmaServiceReference.WebData data) {
            Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest inValue = new Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequest();
            inValue.Body = new Istu.Elma.Auth.ElmaServiceReference.SendMessageToInstanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.instanceId = instanceId;
            inValue.Body.messageTypeName = messageTypeName;
            inValue.Body.data = data;
            return ((Istu.Elma.Auth.ElmaServiceReference.WFPWebServiceSoap)(this)).SendMessageToInstanceAsync(inValue);
        }
    }
}
